
#ifndef FUTURESFRAMEWORK_UNITTESTS_CATCHPORT_HPP
#define FUTURESFRAMEWORK_UNITTESTS_CATCHPORT_HPP

// SYSTEM INCLUDES

#define CATCH_CONFIG_MAIN
// C++ PROJECT INCLUDES
#include "catch/catch.hpp"

#endif
