if( PYTHON_ENABLED )
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} $(python-config --cflags)" )
    set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} $(python-config --cflags)" )
    set( CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} $(python-config --ldflags)")
    set( CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} $(python-config --ldflags)" )
    set( CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} $(python-config --ldflags)")
endif()

if( ${PROCESSOR} MATCHES "aarch64" )
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "c++ flags" )
    set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "c flags" )
    set( CMAKE_EXE_LINKER_FLAGS "{CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "exe linker flags" )
    set( CMAKE_SHARED_LINKER_FLAGS "{CMAKE_SHARED_LINKER_FLAGS}" CACHE STRING "shared linker flags" )
    set( CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS}" CACHE STRING "module linker flags")
else()
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32" CACHE STRING "c++ flags" )
    set( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32" CACHE STRING "c flags" )
    set( CMAKE_EXE_LINKER_FLAGS "{CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "exe linker flags" )
    set( CMAKE_SHARED_LINKER_FLAGS "{CMAKE_SHARED_LINKER_FLAGS}" CACHE STRING "shared linker flags" )
    set( CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS}" CACHE STRING "module linker flags")
endif()

set( CMAKE_CXX_COMPILER "g++" )
set( CMAKE_C_COMPILER "gcc" )
